# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alex Cavallin
email: alex.cavallin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  
  Questo è il sito github di Alex Cavallin. Sono un developer residente a Treviso (IT) di 23 anni.
  Sono Laureato in informatica con un punteggio di 102 e attualmente lavoro sviluppando applicativi web in PHP per un CRM.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.linkedin.com/in/alexcavallin" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  alexpro93

# Build settings
markdown: kramdown
